dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - ./manage migrate
  - echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@myproject.com', 'password')" | python manage.py shell
  - ./manage.py test
